# Generated by Django 4.1.3 on 2023-01-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_volunteer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
